apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: uipod-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: uipod
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: uipod_requests_per_second
        target:
          type: AverageValue
          averageValue: 2